SELECT CLIENT.NAME, COUNT(PROJECT.CLIENT_ID) as PROJECT_COUNT
FROM CLIENT, PROJECT
WHERE CLIENT.ID = PROJECT.CLIENT_ID
GROUP BY name
HAVING COUNT(PROJECT.CLIENT_ID) IN (
    SELECT COUNT(CLIENT_ID)
    FROM PROJECT
    GROUP BY CLIENT_ID
    ORDER BY count(CLIENT_ID) DESC LIMIT 1
)